// ============================================================================
// File: product.dto.ts
// Description: Product Data Transfer Objects (DTOs) for ShopForge — typed interfaces
//              that define the shape of product API request and response payloads
// Key Responsibilities:
//   - Define query parameter contracts for product listing with multi-field filtering
//   - Define creation and update payloads for admin product management
//   - Define response shapes for product lists, detail views, variants, and reviews
//   - Support flash sale pricing as an optional nested structure
// ============================================================================

// ---- Request DTOs ----

/**
 * Product list query parameters — all fields are optional for flexible filtering.
 *
 * Used by the product listing page and search functionality. Multiple
 * filters can be combined (e.g., categoryId + minPrice + maxPrice)
 * for precise product discovery.
 */
export interface ProductListQueryDTO {
  /** Full-text search query — searches name, short description, description, and SKU */
  search?: string
  /** Filter by category ID */
  categoryId?: string
  /** Filter by brand ID */
  brandId?: string
  /** Minimum price filter (inclusive, in dollars) */
  minPrice?: number
  /** Maximum price filter (inclusive, in dollars) */
  maxPrice?: number
  /** Minimum average rating filter (inclusive, 0–5 scale) */
  minRating?: number
  /** Sort strategy — controls the ordering of results */
  sort?: 'newest' | 'price-asc' | 'price-desc' | 'rating' | 'popular'
  /** Page number for pagination (1-indexed) */
  page?: number
  /** Number of products per page */
  limit?: number
  /** Filter to featured products only (for homepage carousels) */
  isFeatured?: boolean
  /** Filter by product tag (e.g., "new-arrival", "summer-sale") */
  tag?: string
}

/**
 * Product detail query — identifies a product by its ID.
 *
 * Note: The service layer also supports slug-based lookups, but this
 * DTO only handles ID-based queries from the API.
 */
export interface ProductDetailQueryDTO {
  /** The product's unique identifier (UUID) */
  id: string
}

/**
 * Create product request payload (admin only).
 *
 * Contains all fields needed to create a new product. The slug and SKU
 * are auto-generated by the service layer from the product name and
 * timestamp respectively, so they are not included here.
 */
export interface CreateProductDTO {
  /** Product display name (used to auto-generate the URL slug) */
  name: string
  /** Full product description (supports HTML/rich text) */
  description: string
  /** Short description for product cards and search results */
  shortDesc?: string
  /** Selling price (in dollars) */
  price: number
  /** Comparison/strike-through price to show savings (in dollars) */
  comparePrice?: number
  /** ID of the category to assign the product to */
  categoryId: string
  /** ID of the brand to assign the product to */
  brandId?: string
  /** Initial stock quantity for the inventory record (defaults to 0) */
  stock?: number
  /** Array of image URLs for the product gallery */
  images?: string[]
  /** Whether the product is featured on the homepage */
  isFeatured?: boolean
  /** Whether the product is a digital download (no shipping required) */
  isDigital?: boolean
  /** Product weight for shipping calculations (in kg) */
  weight?: number
  /** Product dimensions for shipping calculations (e.g., "30x20x10 cm") */
  dimensions?: string
}

/**
 * Update product request payload (admin only).
 *
 * All fields are optional — only the provided fields will be updated.
 * This enables partial updates without requiring the full product data.
 */
export interface UpdateProductDTO {
  /** Updated product name */
  name?: string
  /** Updated product description */
  description?: string
  /** Updated selling price */
  price?: number
  /** Updated comparison price */
  comparePrice?: number
  /** Toggle product visibility in the storefront */
  isActive?: boolean
  /** Toggle featured status for homepage display */
  isFeatured?: boolean
}

// ---- Response DTOs ----

/**
 * Product list item — a simplified product representation for listing pages.
 *
 * Optimised for performance by excluding heavy fields like full description,
 * variants, and reviews. Includes enough data for product cards: image,
 * price, rating, category, brand, and inventory summary.
 */
export interface ProductListItemDTO {
  /** Unique product identifier (UUID) */
  id: string
  /** Product display name */
  name: string
  /** URL-friendly slug for product detail pages */
  slug: string
  /** Short description for product cards, or null */
  shortDesc: string | null
  /** Current selling price (in dollars) */
  price: number
  /** Comparison/strike-through price to show savings, or null */
  comparePrice: number | null
  /** JSON-stringified array of image URLs */
  images: string
  /** Average rating across all approved reviews (0–5 scale) */
  avgRating: number
  /** Total number of approved reviews */
  reviewCount: number
  /** Total units sold across all time */
  totalSold: number
  /** Whether the product is featured on the homepage */
  isFeatured: boolean
  /** Whether the product is visible in the storefront */
  isActive: boolean
  /** Category information for breadcrumb navigation */
  category: { id: string; name: string; slug: string }
  /** Brand information, or null if unbranded */
  brand: { id: string; name: string; slug: string } | null
  /** Inventory records with available and reserved quantities */
  inventory: { quantity: number; reserved: number }[]
  /** Tags associated with this product */
  tags: { tag: string }[]
  /** Active flash sale pricing, if the product is part of a current flash sale */
  flashSaleProduct?: Array<{
    /** Discounted sale price during the flash sale */
    salePrice: number
    /** Flash sale details including timing and active status */
    flashSale: { isActive: boolean; startsAt: string; endsAt: string }
  }>
}

/**
 * Product detail — the complete product representation for detail pages.
 *
 * Includes all fields from the list item plus full description, variants,
 * inventory details, and approved reviews. This is the heaviest product
 * payload and should only be used for the product detail page.
 */
export interface ProductDetailDTO {
  /** Unique product identifier (UUID) */
  id: string
  /** Product display name */
  name: string
  /** URL-friendly slug */
  slug: string
  /** Full product description (may contain HTML) */
  description: string
  /** Short description for product cards, or null */
  shortDesc: string | null
  /** Stock Keeping Unit identifier */
  sku: string
  /** Current selling price (in dollars) */
  price: number
  /** Comparison/strike-through price, or null */
  comparePrice: number | null
  /** Internal cost price for margin calculations, or null */
  costPrice: number | null
  /** JSON-stringified array of image URLs */
  images: string
  /** Whether the product is visible in the storefront */
  isActive: boolean
  /** Whether the product is featured on the homepage */
  isFeatured: boolean
  /** Product weight (in kg), or null */
  weight: number | null
  /** Product dimensions string (e.g., "30x20x10 cm"), or null */
  dimensions: string | null
  /** Average rating across approved reviews */
  avgRating: number
  /** Total number of approved reviews */
  reviewCount: number
  /** Total units sold */
  totalSold: number
  /** Category information */
  category: { id: string; name: string; slug: string }
  /** Brand information, or null */
  brand: { id: string; name: string; slug: string } | null
  /** Available product variants (e.g., different sizes, colors) */
  variants: ProductVariantDTO[]
  /** Detailed inventory records with thresholds */
  inventory: Array<{ id: string; quantity: number; reserved: number; lowStockThreshold: number; sku: string }>
  /** Tags associated with this product */
  tags: { tag: string }[]
  /** Approved reviews for this product (limited to 50 most recent) */
  reviews: ReviewDTO[]
  /** Active flash sale pricing, if applicable */
  flashSaleProduct?: Array<{
    /** Discounted sale price */
    salePrice: number
    /** Flash sale details */
    flashSale: { isActive: boolean; startsAt: string; endsAt: string }
  }>
}

/**
 * Product variant — a specific version of a product (e.g., size, color).
 *
 * Each variant can have its own price, comparison price, image, and
 * inventory record. Variants share the parent product's description
 * and category.
 */
export interface ProductVariantDTO {
  /** Unique variant identifier (UUID) */
  id: string
  /** Variant display name (e.g., "Large / Red") */
  name: string
  /** Variant-specific SKU */
  sku: string
  /** Variant price (overrides parent product price if set) */
  price: number
  /** Variant comparison price, or null */
  comparePrice: number | null
  /** Variant-specific image URL, or null (falls back to parent product images) */
  images: string | null
  /** JSON-stringified attribute map (e.g., {"size": "L", "color": "Red"}) */
  attributes: string
  /** Whether this variant is available for purchase */
  isActive: boolean
  /** Variant-specific inventory record, or null if not tracked separately */
  inventory?: { id: string; quantity: number; reserved: number } | null
}

/**
 * Product review — a customer's rating and feedback for a product.
 *
 * Reviews require admin approval before being publicly visible
 * (`isApproved` filter is applied at the repository level).
 * Helpful votes allow other customers to indicate review usefulness.
 */
export interface ReviewDTO {
  /** Unique review identifier (UUID) */
  id: string
  /** Star rating from 1 to 5 */
  rating: number
  /** Review title/summary, or null */
  title: string | null
  /** Full review text, or null */
  content: string | null
  /** JSON-stringified array of review image URLs, or null */
  images: string | null
  /** Whether the reviewer is a verified purchaser */
  isVerified: boolean
  /** Number of "helpful" upvotes from other customers */
  helpfulYes: number
  /** Number of "not helpful" downvotes from other customers */
  helpfulNo: number
  /** ISO 8601 timestamp of when the review was submitted */
  createdAt: string
  /** Reviewer's public profile information */
  user: { id: string; name: string | null; image: string | null }
}

/**
 * Paginated product list response — wraps the product array with pagination metadata.
 *
 * The `totalPages` field is pre-calculated so the frontend can render
 * page navigation without additional division logic.
 */
export interface PaginatedProductsDTO {
  /** Array of products for the current page */
  items: ProductListItemDTO[]
  /** Total number of products matching the filters */
  total: number
  /** Current page number (1-indexed) */
  page: number
  /** Number of products per page */
  limit: number
  /** Total number of pages (ceil(total / limit)) */
  totalPages: number
}
