/**
 * @file use-toast.ts
 * @description Toast notification system following the shadcn/ui pattern.
 *
 * Inspired by the react-hot-toast library, this module provides a global toast
 * notification system built on React's external store pattern (useSyncExternalStore
 * style, via manual listener management).
 *
 * Key Responsibilities:
 * - Manages a queue of toast notifications with a configurable display limit
 * - Provides a `toast()` function for imperatively creating toasts from anywhere
 *   (including outside React component trees, e.g., in API handlers)
 * - Provides a `useToast()` hook for React components to subscribe to toast state
 * - Supports toast lifecycle: add → update → dismiss → auto-remove after delay
 * - Handles toast dismissal with a delayed removal queue to allow exit animations
 * - Uses a reducer-based state machine for predictable state transitions
 *
 * Architecture:
 * - **State**: Managed by a reducer (`reducer`) over a `memoryState` variable
 * - **Broadcasting**: A `listeners` array of subscriber callbacks is notified
 *   on every state change, enabling React components to re-render
 * - **Dispatch**: The `dispatch()` function applies actions through the reducer
 *   and broadcasts the new state to all listeners
 * - **Auto-removal**: Dismissed toasts are queued for removal after a delay
 *   via `addToRemoveQueue()`, allowing CSS exit animations to complete
 */

"use client"

// Inspired by react-hot-toast library
import * as React from "react"

import type {
  ToastActionElement,
  ToastProps,
} from "@/components/ui/toast"

/**
 * Maximum number of toasts visible at the same time.
 * Older toasts are pruned when the limit is exceeded.
 */
const TOAST_LIMIT = 1

/**
 * Delay in milliseconds before a dismissed toast is removed from the DOM.
 *
 * Set to an intentionally large value (1,000,000ms ≈ 16 minutes) to ensure
 * the CSS exit animation completes before the toast element is removed.
 * The actual visual dismissal is controlled by setting `open: false`, which
 * triggers the Radix UI dismiss animation. The DOM removal happens later.
 */
const TOAST_REMOVE_DELAY = 1000000

/**
 * Extended toast type that combines Radix UI's ToastProps with custom fields.
 *
 * This represents a fully resolved toast instance stored in state, including
 * the generated ID and optional action button.
 *
 * @property id - Unique identifier generated by `genId()`
 * @property title - Optional title content (supports React nodes for rich formatting)
 * @property description - Optional body content (supports React nodes)
 * @property action - Optional action button element (e.g., "Undo" button)
 */
type ToasterToast = ToastProps & {
  id: string
  title?: React.ReactNode
  description?: React.ReactNode
  action?: ToastActionElement
}

/**
 * Action type constants for the toast reducer.
 *
 * Using `as const` ensures these are treated as literal string types
 * rather than generic `string`, enabling exhaustive switch/case checking.
 *
 * - ADD_TOAST: Create a new toast and add it to the queue
 * - UPDATE_TOAST: Modify an existing toast's properties (e.g., update text)
 * - DISMISS_TOAST: Mark a toast as closed (sets `open: false`) and queue it for removal
 * - REMOVE_TOAST: Remove a toast from the state entirely (after animation completes)
 */
const actionTypes = {
  ADD_TOAST: "ADD_TOAST",
  UPDATE_TOAST: "UPDATE_TOAST",
  DISMISS_TOAST: "DISMISS_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",
} as const

/** Auto-incrementing counter for generating unique toast IDs */
let count = 0

/**
 * Generate a unique toast ID using an auto-incrementing counter.
 *
 * The counter wraps around at `Number.MAX_SAFE_INTEGER` to prevent
 * integer overflow in long-running sessions. In practice, this limit
 * is virtually unreachable.
 *
 * @returns A unique string ID for a new toast
 */
function genId() {
  count = (count + 1) % Number.MAX_SAFE_INTEGER
  return count.toString()
}

/**
 * Derived type from the `actionTypes` constant object.
 * Provides union type: "ADD_TOAST" | "UPDATE_TOAST" | "DISMISS_TOAST" | "REMOVE_TOAST"
 */
type ActionType = typeof actionTypes

/**
 * Discriminated union of all possible toast reducer actions.
 *
 * Each action type carries a different payload shape:
 * - ADD_TOAST carries the full toast object
 * - UPDATE_TOAST carries a partial toast (only fields to update)
 * - DISMISS_TOAST and REMOVE_TOAST carry an optional toastId;
 *   when omitted, the action applies to ALL toasts
 */
type Action =
  | {
    type: ActionType["ADD_TOAST"]
    toast: ToasterToast
  }
  | {
    type: ActionType["UPDATE_TOAST"]
    toast: Partial<ToasterToast>
  }
  | {
    type: ActionType["DISMISS_TOAST"]
    toastId?: ToasterToast["id"]
  }
  | {
    type: ActionType["REMOVE_TOAST"]
    toastId?: ToasterToast["id"]
  }

/**
 * Shape of the toast reducer's state.
 * Simply holds the ordered array of active toasts.
 */
interface State {
  toasts: ToasterToast[]
}

/**
 * Map of toast IDs to their pending removal timeouts.
 *
 * This ensures that only one removal timeout is scheduled per toast,
 * even if `addToRemoveQueue` is called multiple times for the same toast
 * (e.g., due to rapid dismiss + auto-dismiss).
 */
const toastTimeouts = new Map<string, ReturnType<typeof setTimeout>>()

/**
 * Schedule a toast for removal from the DOM after the configured delay.
 *
 * This function implements the "dismiss then remove" two-phase pattern:
 * 1. A toast is first *dismissed* (sets `open: false` to trigger exit animation)
 * 2. After `TOAST_REMOVE_DELAY`, the toast is *removed* from state entirely
 *
 * The guard `if (toastTimeouts.has(toastId))` prevents duplicate timers
 * for the same toast, which could cause premature removal or errors.
 *
 * @param toastId - The ID of the toast to schedule for removal
 */
const addToRemoveQueue = (toastId: string) => {
  if (toastTimeouts.has(toastId)) {
    return
  }

  const timeout = setTimeout(() => {
    // Clean up the timeout entry after it fires
    toastTimeouts.delete(toastId)
    // Dispatch the REMOVE action to actually delete the toast from state
    dispatch({
      type: "REMOVE_TOAST",
      toastId: toastId,
    })
  }, TOAST_REMOVE_DELAY)

  toastTimeouts.set(toastId, timeout)
}

/**
 * Reducer function for toast state transitions.
 *
 * Handles four action types with the following behavior:
 *
 * - **ADD_TOAST**: Prepends the new toast and enforces `TOAST_LIMIT`
 *   by slicing the array. This means new toasts push out older ones.
 *
 * - **UPDATE_TOAST**: Merges the partial update into the matching toast
 *   (identified by `id`). Useful for dynamically changing toast content.
 *
 * - **DISMISS_TOAST**: Sets `open: false` on the matching toast(s) and
 *   queues them for removal. Has a side effect of calling `addToRemoveQueue`.
 *   If `toastId` is undefined, ALL toasts are dismissed.
 *
 * - **REMOVE_TOAST**: Removes the toast from state entirely. If `toastId`
 *   is undefined, all toasts are removed (e.g., on "clear all" action).
 *
 * @param state - The current toast state
 * @param action - The dispatched action describing the state change
 * @returns The new toast state after applying the action
 */
export const reducer = (state: State, action: Action): State => {
  switch (action.type) {
    case "ADD_TOAST":
      return {
        ...state,
        // Prepend new toast and enforce the display limit
        toasts: [action.toast, ...state.toasts].slice(0, TOAST_LIMIT),
      }

    case "UPDATE_TOAST":
      return {
        ...state,
        // Merge the partial update into the matching toast
        toasts: state.toasts.map((t) =>
          t.id === action.toast.id ? { ...t, ...action.toast } : t
        ),
      }

    case "DISMISS_TOAST": {
      const { toastId } = action

      // Side effect: schedule the toast(s) for removal after animation
      if (toastId) {
        addToRemoveQueue(toastId)
      } else {
        // No specific toastId — dismiss ALL toasts
        state.toasts.forEach((toast) => {
          addToRemoveQueue(toast.id)
        })
      }

      return {
        ...state,
        // Mark the toast(s) as closed to trigger exit animations
        toasts: state.toasts.map((t) =>
          t.id === toastId || toastId === undefined
            ? {
              ...t,
              open: false,
            }
            : t
        ),
      }
    }
    case "REMOVE_TOAST":
      if (action.toastId === undefined) {
        // Remove ALL toasts
        return {
          ...state,
          toasts: [],
        }
      }
      // Remove only the specified toast
      return {
        ...state,
        toasts: state.toasts.filter((t) => t.id !== action.toastId),
      }
  }
}

/**
 * Array of subscriber callbacks registered by `useToast()` hooks.
 *
 * Each hook pushes its `setState` function here, and `dispatch()` calls
 * all of them whenever state changes. This is the core of the external
 * store pattern that allows non-React code (like `toast()`) to trigger
 * React re-renders.
 */
const listeners: Array<(state: State) => void> = []

/** The in-memory toast state, maintained by the reducer */
let memoryState: State = { toasts: [] }

/**
 * Dispatch an action to the toast reducer and notify all subscribers.
 *
 * This is the central dispatch function that:
 * 1. Applies the action to the current `memoryState` via the `reducer`
 * 2. Updates `memoryState` with the new state
 * 3. Calls every registered listener with the new state, triggering
 *    React re-renders in components using `useToast()`
 *
 * @param action - The action to dispatch
 */
function dispatch(action: Action) {
  memoryState = reducer(memoryState, action)
  listeners.forEach((listener) => {
    listener(memoryState)
  })
}

/**
 * Input type for the `toast()` function.
 *
 * Omits `id` since it is auto-generated, and omits internal fields
 * like `onOpenChange` which are managed by the toast system itself.
 */
type Toast = Omit<ToasterToast, "id">

/**
 * Imperatively create and display a toast notification.
 *
 * This is the primary API for showing toasts. It can be called from
 * anywhere — inside React components, event handlers, API callbacks,
 * or even outside the React tree entirely.
 *
 * The function:
 * 1. Generates a unique ID for the toast
 * 2. Dispatches an ADD_TOAST action with `open: true`
 * 3. Sets up `onOpenChange` to auto-dismiss when the toast is closed
 * 4. Returns an object with `id`, `dismiss()`, and `update()` methods
 *   for controlling the toast after creation
 *
 * @param props - Toast properties (title, description, variant, action, etc.)
 * @returns An object with:
 *   - `id` — The unique toast ID
 *   - `dismiss` — Function to dismiss this specific toast
 *   - `update` — Function to update this toast's properties
 *
 * @example
 * // Simple toast
 * toast({ title: "Item added to cart" })
 *
 * // Toast with action button
 * toast({
 *   title: "Item removed",
 *   description: "Your item has been removed from the cart.",
 *   action: <UndoButton onClick={handleUndo} />
 * })
 *
 * // Updating an existing toast
 * const { id, update, dismiss } = toast({ title: "Saving..." })
 * update({ title: "Saved successfully!" })
 * dismiss()
 */
function toast({ ...props }: Toast) {
  const id = genId()

  /**
   * Update this toast's properties after creation.
   * Merges the provided partial props with the existing toast.
   * @param props - Partial toast properties to update
   */
  const update = (props: ToasterToast) =>
    dispatch({
      type: "UPDATE_TOAST",
      toast: { ...props, id },
    })

  /** Dismiss this toast, triggering the dismiss→remove lifecycle */
  const dismiss = () => dispatch({ type: "DISMISS_TOAST", toastId: id })

  dispatch({
    type: "ADD_TOAST",
    toast: {
      ...props,
      id,
      open: true,
      // Wire up the Radix UI onOpenChange callback to auto-dismiss
      // when the user clicks the close button or swipes the toast away
      onOpenChange: (open) => {
        if (!open) dismiss()
      },
    },
  })

  return {
    id: id,
    dismiss,
    update,
  }
}

/**
 * React hook for subscribing to the toast notification state.
 *
 * Implements the external store pattern manually:
 * 1. On mount, registers a listener (the component's `setState`) in the
 *    global `listeners` array
 * 2. On every `dispatch()`, all listeners are called with the new state,
 *    triggering a re-render of this component
 * 3. On unmount, the listener is removed to prevent memory leaks
 *
 * Returns the current toast state along with the `toast()` function
 * and a `dismiss()` helper for convenience.
 *
 * @returns An object containing:
 *   - `toasts` — The current array of active toasts
 *   - `toast` — The imperative toast creation function
 *   - `dismiss` — Function to dismiss a specific toast (by ID) or all toasts
 *
 * @example
 * function MyComponent() {
 *   const { toast, dismiss } = useToast()
 *
 *   return (
 *     <button onClick={() => toast({ title: "Hello!" })}>
 *       Show Toast
 *     </button>
 *   )
 * }
 */
function useToast() {
  const [state, setState] = React.useState<State>(memoryState)

  React.useEffect(() => {
    // Subscribe to state changes by registering this component's setState
    listeners.push(setState)
    return () => {
      // Unsubscribe on unmount to prevent stale references and memory leaks
      const index = listeners.indexOf(setState)
      if (index > -1) {
        listeners.splice(index, 1)
      }
    }
  }, [state])

  return {
    ...state,
    toast,
    dismiss: (toastId?: string) => dispatch({ type: "DISMISS_TOAST", toastId }),
  }
}

export { useToast, toast }
