/**
 * @file error.tsx
 * @description Error boundary component for the ShopForge application.
 * This is a Next.js convention-based error page that automatically catches runtime
 * errors thrown by any Server Component or Client Component within the `/` route segment.
 * It provides a user-friendly UI with retry and home-navigation options.
 *
 * Key Responsibilities:
 * - Catches unexpected runtime errors within the route segment
 * - Logs the error to the browser console for debugging
 * - Displays the error message to the user (when available)
 * - Offers a "Try Again" button that re-invokes the failed render via `reset()`
 * - Offers a "Go Home" button that navigates to the root route
 *
 * @see https://nextjs.org/docs/app/api-reference/file-conventions/error
 */

'use client'

import { useEffect } from 'react'
import { Button } from "@/shared/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card"
import { AlertTriangle, RefreshCw, Home } from 'lucide-react'

/**
 * Error boundary props provided by Next.js.
 *
 * @interface ErrorProps
 * @property {Error & { digest?: string }} error - The caught error object.
 *   The optional `digest` property is a unique hash generated by Next.js for
 *   server-side errors, useful for cross-referencing with server logs.
 * @property {() => void} reset - A function that attempts to re-render the
 *   failed route segment. Useful when the error was transient (e.g. network timeout).
 */
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  /**
   * Log the error to the console whenever it changes.
   * Using a dependency array of `[error]` ensures the log is updated if
   * the error object is replaced (e.g. after a failed retry produces a new error).
   */
  useEffect(() => {
    console.error('[Error Boundary]', error)
  }, [error])

  return (
    <div className="flex min-h-[60vh] items-center justify-center p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          {/* Visual indicator — red alert circle with warning icon */}
          <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-red-100 dark:bg-red-900/20">
            <AlertTriangle className="h-8 w-8 text-red-600 dark:text-red-400" />
          </div>
          <CardTitle className="text-2xl">Something went wrong</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-center text-muted-foreground">
            An unexpected error occurred. Please try again.
          </p>
          {/* Conditionally render the error message so users see what went wrong,
              but gracefully handle cases where the message might be undefined */}
          {error.message && (
            <p className="text-center text-sm text-red-500 bg-red-50 dark:bg-red-900/10 rounded-md p-2">
              {error.message}
            </p>
          )}
          <div className="flex gap-3 justify-center">
            {/* "Try Again" calls reset() which re-triggers the route segment render.
                This can resolve transient errors like network timeouts. */}
            <Button onClick={reset} variant="outline" className="gap-2">
              <RefreshCw className="h-4 w-4" />
              Try Again
            </Button>
            {/* "Go Home" performs a full page navigation to the root route,
                effectively escaping the errored route segment entirely. */}
            <Button onClick={() => (window.location.href = '/')} className="gap-2">
              <Home className="h-4 w-4" />
              Go Home
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
